### ISSUE TITLE
Missing API key error

### ISSUE THREAD

**Issue by tblake84** [ff36/halo-plugin-gmap#14]
Attempting to add @Latitude/@Longitude information via a sector's Custom Data section results in a "missing API key" error.

Have been using my own key for the gmap plugin and it works but need to know where our key should be entered for this function to work.

**Comment by tarkal** [comment]
Could you provide a sample format of an API key. 

I will add a setting to the plugin.

Tarka L'Herpiniere

On Wed, Aug 24, 2016 at 19:10 tblake84

<
mailto:tblake84 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Attempting to add @Latitude/
https://github.com/Longitude
information via a sector's Custom Data section results in a "missing API key" error.

Have been using my own key for the gmap plugin and it works but need to know where our key should be entered for this function to work.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/ff36/halo-plugin-gmap/issues/14
, or

**Comment by tblake84** [comment]
Last line in /opt/halo/app/plugin/716750546/gmap-1.0.1/classes/html/index.html reads:



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXX"></script>


The key I have is a 39 digit alphanumeric key but I am not sure if this is a standard format or not.

-----------------
W. Tim Blake, J.D.


On Aug 25, 2016, at 03:44 AM, tarkal <notifications@github.com> wrote:


Could you provide a sample format of an API key. 

I will add a setting to the plugin.

Tarka L'Herpiniere

On Wed, Aug 24, 2016 at 19:10 tblake84

<
mailto:tblake84 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Attempting to add @Latitude/
https://github.com/Longitude
information via a sector's Custom Data section results in a "missing API key" error.

Have been using my own key for the gmap plugin and it works but need to know where our key should be entered for this function to work.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/ff36/halo-plugin-gmap/issues/14
, or

**Comment by tarkal** [comment]
Fixed in latest release
